### ISSUE TITLE
Storing keys of recipient's.

### ISSUE THREAD

**Issue by B00jan** [christophhagen/libsignal-protocol-swift#4]
I'm new to Swift so maybe this question is stupid, but here it is. Is there a method in this lib to save recipient's keys on a safe place when i receive them from server or shoud i write them my self?

**Comment by BaranEm** [comment]
You only fetch for the recipient's public keys when you want to build a session, right? To build an session you do the following: https://github.com/christophhagen/libsignal-protocol-swift#building-a-session-with-a-downloaded-pre-key-bundle.

Building the session is internally done by the library. What you need to do in your project is to write the persistent store logic for your store delegate's: https://github.com/christophhagen/libsignal-protocol-swift#client-install-time. 

When you did setup everything successfully you only invoke `try SessionBuilder(for: address, in: store).process(preKeyBundle: retrievedBundle)` (first link above, second code line).
Your `SignalStore` then invokes all necessary store delegate methods in order to store and receive the recipients public keys.

I highly recommend writing unit test's for your store delegate in order to check whether keys are stored and received correctly.

If you need to see things in action I also recommend checking out the source code of the Signal iOS app: https://github.com/signalapp/Signal-iOS

**Comment by B00jan** [comment]
Fetching only when building a session, that part i understand. So TestStores that are under TestImplementation are not storing key's on safe place, they are just for presentation purpose. I need to add logic in them to store keys some place safe? I thought that that part is covered by lib, and StoreWrappers, and that C  is doing that for me.

**Comment by crossle** [comment]
Yes, you need store keys to Database or file

**Comment by BaranEm** [comment]
It is like @crossle did said. The library does not cover storing keys persistently for you. If you don't know how and where to store the keys have a look at YapDatabase (https://github.com/yapstudios/YapDatabase). Its perfect for that work.

**Comment by B00jan** [comment]
Thank you for your answers and suggestions.
